# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TikiHomeTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TikiHomeTest
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'MBProgressHUD'
  pod 'Bolts-Swift'
  pod 'SDWebImage'
  pod 'ObjectMapper+Realm'

  target 'TikiHomeTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TikiHomeTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
